#!/usr/bin/env python
# coding: utf-8

from utilities import get_query_config, build_replacements

configuration = get_query_config()

print("# This file is autogenerated.  Do not edit.\n")

for target in configuration['queries']:
    query_info = configuration['queries'][target]
    substitution_files = [x for (_, x) in build_replacements(configuration['substitutions'], query_info['substitutions'], only_files = True)]
    string = f"{query_info['query']}"
    for file_name in substitution_files:
        string += f" {file_name}"
    print(f"{target}: {string}\n\tpython3 scripts/download.py {target}\n")
    if query_info['make_csv']:
        csv_info = query_info['csv_info']
        new_target = csv_info['output']
        string = f"{new_target}: {target}\n\tpython3 scripts/boa-to-csv.py"
        if 'tests' in csv_info.keys():
            for test in csv_info['tests']:
                string += f" -t \"{test}\""
        if 'drop' in csv_info.keys():
            string += f" -d {csv_info['drop']}"
        if 'header' in csv_info.keys():
            string += f" --header {csv_info['header']}"
        if 'index' in csv_info.keys():
            string += f" --numidx {csv_info['index']}"
        string += f" {target} > {new_target}\n"
        print(string)
